### ISSUE TITLE
Google HTML tags issue

### ISSUE THREAD

**Issue by etsanov** [soimort/translate-shell#139]
Hi,
Great tool, but I am having a small problem. I read, and it seems that Google has plain text and HTML formats. The default should be HTML. However, when I include `<br>` for example, the translation returns "u003cbr/u003e". Here is my code:

`foreach($parentCollection as $parentID) {
    $parentProducts = Mage::getModel( 'catalog/product' )->load( $parentID->getId() );
    $sku = $parentProducts->getSku();
    $description_en = $parentProducts->getDescription();
    $description_bg = shell_exec("translate/trans -b -e google \"$description_en\" :bg");
    fputcsv($fp, array($sku, $description_en, $description_bg), ",");`

Is there a workaround? Is there a setting I need to specify in regard to the HTML default support. Please advise! Thank you again for a wonderful translate tool!

**Comment by soimort** [comment]
I don't understand what your problem is.

**Comment by etsanov** [comment]
I am sorry for the confusion. I appreciate your fast reply. Here is an example:

`./trans -e google -b  en:bg "<br>word</br>"`
`u003cbru003e дума u003c / BR u003e`

However, when using bing, there's no problem:

`./trans -e bing -b en:bg "<br>word</br>"`
`<br>думата</br>`

As you can see, when using Google, the translated text breaks the proper tagging. Moreover, sometimes, the text inside the tag (e.g. br) gets translated (as if it says not "br" but "bra"). Instead of getting

`</br>`

I get

`u003c / BR u003e`

Or I could also get this translated to, for example:

`u003cbru003e u003c / сутиен u003e` (like <bra/>)
or
`u003cbru003e u003c / брат u003e` (like <bro/>)

I am sorry if I am not explaining this good enough. Let me know if you need more details.

**Comment by etsanov** [comment]
Right now I am using quite the sed one-liner to replace strange tag occurrences:

`sed -i -e 's/u003e/>/g' -e 's/u003c/</g' -e 's/< сутиен/<br/g' -e 's/& Nbsp/&nbsp/g' -e 's/< Бар \/ >/<br\/>/g' -e 's/< Се \/ >/<br\/>/g' -e 's/< Бъде \/ >/<br\/>/g' -e 's/< От \/ >/<br\/>/g' -e 's/< Бар >/<br>/g' -e 's/< Сутиен \/ >/<br\/>/g' -e 's/< примки Br\//<br\/>/g' -e 's/< Брато \/ >/<br\/>/g' -e 's/< бар \/ >/<br\/>/g' -e 's/<Бразилски \/  >/<br\/>/g' -e 's/< примки Br2 колан/<br\/>/g' -e 's/<Бразилски.  \/ >/<br\/>/g' -e 's/<Бразилски/<br>/g'`

However, I would really appreciate it if the problem could be fixed somehow.
Thanks!

**Comment by soimort** [comment]
Thanks for your explanation in details. Short answer: Unlike Bing Translator, Google Translate API returns escaped Unicode (`\u003c`) instead of literal chars (`<`), thus those mysterious "u"-strings appear. Unfortunately AWK has no built-in method to convert between escaped Unicode characters and literal chars (because it's such an old-fashioned language), so there's no easy workaround on this without calling an external program.

I would suggest not trying to directly translate HTML tags via Google Translate; in most cases they're not even semantically valid. But for sure, this issue needs to be fixed anyway.

**Comment by soimort** [comment]
Regarding HTML tags: this is fixed by 1030f05, though general Unicode char escaping is not implemented.

**Comment by etsanov** [comment]
I use the self-contained executable ./trans. The issue with < and > still exists there. Will that be updated too, or should I install the program the other way?

**Comment by soimort** [comment]
> I use the self-contained executable ./trans. The issue with < and > still exists there. Will that be updated too, or should I install the program the other way?

Please report your `./trans -V`.

**Comment by etsanov** [comment]
It was 0.9.5. I updated it after your last reply, but it seems that I did it too soon. Thank you! Using 0.9.6 now, the problem no longer occurs.

**Comment by benoit-roue** [comment]
Hello, 
I has been fixed for "<" and ">". Nice.
But there is the same issue with "=" sign. 
```bash
$  trans -b :en "ceci est un = texte < >"
this is a u003d text < >
```

Here is my version
```bash
$ trans -V
Translate Shell       0.9.6.11

platform              Linux
terminal type         xterm-256color
bi-di emulator        [N/A]
gawk (GNU Awk)        5.0.1
fribidi (GNU FriBidi) 1.0.8
audio player          [NOT INSTALLED]
terminal pager        less
web browser           xdg-open
user locale           C.UTF-8 (Emoji)
home language         emj
source language       auto
target language       emj
translation engine    google
proxy                 [NONE]
user-agent            Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/602.1 (KHTML, like Gecko) Version/8.0 Safari/602.1 Epiphany/3.18.2
ip version            [DEFAULT]
theme                 default
init file             [NONE]
```

**Comment by soimort** [comment]
> Hello, I has been fixed for "<" and ">". Nice. But there is the same issue with "=" sign.
> 
> ```shell
> $  trans -b :en "ceci est un = texte < >"
> this is a u003d text < >
> ```
> 
> Here is my version
> 
> ```shell
> $ trans -V
> Translate Shell       0.9.6.11
> 
> platform              Linux
> terminal type         xterm-256color
> bi-di emulator        [N/A]
> gawk (GNU Awk)        5.0.1
> fribidi (GNU FriBidi) 1.0.8
> audio player          [NOT INSTALLED]
> terminal pager        less
> web browser           xdg-open
> user locale           C.UTF-8 (Emoji)
> home language         emj
> source language       auto
> target language       emj
> translation engine    google
> proxy                 [NONE]
> user-agent            Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/602.1 (KHTML, like Gecko) Version/8.0 Safari/602.1 Epiphany/3.18.2
> ip version            [DEFAULT]
> theme                 default
> init file             [NONE]
> ```

This was reported in #429 and #420, fixed by d3e0836146addb62ba7b1b18e7bc17766460d5c3 (currently available only in `develop` branch).
